CREATE TABLE IF NOT EXISTS playlist_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  media_id INTEGER NOT NULL,
  "order" INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (media_id) REFERENCES media(id) ON DELETE CASCADE
);
